# Matriz identidad

In [5]:
import numpy as np

In [6]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [8]:
A = np.array([[4,7],[2,6]])
A

array([[4, 7],
       [2, 6]])

In [9]:
A @ I

array([[4., 7.],
       [2., 6.]])

# Determinante

In [10]:
np.linalg.det(A)

10.000000000000002

In [11]:
A1 = np.array([[1,1,0],[2,-1,2],[0,3,0]])
A1

array([[ 1,  1,  0],
       [ 2, -1,  2],
       [ 0,  3,  0]])

In [14]:
np.linalg.det(A1)

-6.0

# Matriz transpuesta

In [15]:
A2 = np.arange(6).reshape(3,2)
A2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
np.transpose(A2)

array([[0, 2, 4],
       [1, 3, 5]])

# Matriz inversa

In [18]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [19]:
A1_inv = np.linalg.inv(A1)
A1_inv

array([[ 1.        ,  0.        , -0.33333333],
       [ 0.        ,  0.        ,  0.33333333],
       [-1.        ,  0.5       ,  0.5       ]])