In [2]:
import numpy as np 

In [3]:
# Creando una lista normal de python
v1 = [2,4,6]

In [4]:
# Creando un arrgelo/vector de numpy
v2 = np.array([2,4,6])

In [5]:
type(v1)

list

In [6]:
type(v2)

numpy.ndarray

In [7]:
# Crea un vector con unos, del tamaño que yo le indique en el argumento
v3 = np.ones(3)
v3

array([1., 1., 1.])

In [8]:
# Crear un vector dentro de un rango especificado (inicio, fin (hasta antes de))
v4 = np.arange(1,8)
v4

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# suma con listas de python
v5 = [1,2,3,4]
v6 = [5,6,7,8]

In [10]:
v5+v6

[1, 2, 3, 4, 5, 6, 7, 8]

In [15]:
v5-v6

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [18]:
v5 * 7

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [13]:
#suma con arreglos/vectores de numpy
v7 = np.array([1,2,3,4])
v8 = np.array([5,6,7,8])

In [14]:
v7+v8

array([ 6,  8, 10, 12])

In [17]:
#resta
v7-v8

array([-4, -4, -4, -4])

In [19]:
# multiplicación
v7*7

array([ 7, 14, 21, 28])

In [21]:
# Producto punto, escalar o interior

x = np.array([1,2,3])
y = np.array([4,5,6])

sum(x*y)

32

In [22]:
np.dot(x,y)

32

In [23]:
#Calculando la norma

x1 = np.array([1,2,3,4])
np.linalg.norm(x1)

5.477225575051661

In [26]:
# Operaciones con matrices

A = np.array([[1,3,2],
             [1,0,0],
             [1,2,2]])
A

array([[1, 3, 2],
       [1, 0, 0],
       [1, 2, 2]])

In [27]:
# Multiplicación por escalar
A * 2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [28]:
B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])

In [29]:
# Suma de matrices
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [30]:
# Resta de matrices
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [31]:
# Para ver la dimensión de una matriz
A.shape

(3, 3)

In [32]:
# Para ver la cantidad de elementos
A.size

9

In [33]:
# Multiplicación de matrices

A1 = np.arange(1,13).reshape(3,4)
A1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
B1 = np.arange(8).reshape(4,2)
B1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [35]:
A1 @ B1

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [36]:
B1 @ A1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [3]:
# Matriz identidad
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [4]:
A = np.array([[4,7],
              [2,6]])
A

array([[4, 7],
       [2, 6]])

In [5]:
# Multiplicar matriz cuadrada por su matriz identidad
A @ I

array([[4., 7.],
       [2., 6.]])

In [6]:
# Calculo del determinante
np.linalg.det(A)

10.000000000000002

In [8]:
B = np.array([[4,7,1],
              [2,6,1],
              [1,1,1]])
np.linalg.det(B)

9.000000000000002

In [9]:
# Matriz transpuesta

C = np.arange(6).reshape(3,2)
C

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
np.transpose(C)

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
#Calculando la matriz inversa

A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [13]:
D = np.array([[1,1,0],
              [2,-1,2],
              [0,3,0]])

In [15]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 1.        ,  0.        , -0.33333333],
       [ 0.        ,  0.        ,  0.33333333],
       [-1.        ,  0.5       ,  0.5       ]])